engines:
  duplication:
    enabled: true
    exclude_paths:
    - "test/"
    config:
      languages:
        javascript:
          mass_threshold: 45
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
