env:
  global:
    - CC_TEST_REPORTER_ID=ada7aae99d72b18edab8d25e248d3c580ae50ff265a54172c425a378db5f643d
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false"  ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: node_js

node_js:
  - "7"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - npm test
  - npm run test-demo
